# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: probe.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'probe.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bprobe.proto\x12\x05probe\"J\n\x0cProbeRequest\x12\x1c\n\x14\x65ncryption_algorithm\x18\x01 \x01(\t\x12\x1c\n\x14validation_algorithm\x18\x02 \x01(\t\" \n\rProbeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x42\n\x0cProbeService\x12\x32\n\x05Probe\x12\x13.probe.ProbeRequest\x1a\x14.probe.ProbeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'probe_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROBEREQUEST']._serialized_start=22
  _globals['_PROBEREQUEST']._serialized_end=96
  _globals['_PROBERESPONSE']._serialized_start=98
  _globals['_PROBERESPONSE']._serialized_end=130
  _globals['_PROBESERVICE']._serialized_start=132
  _globals['_PROBESERVICE']._serialized_end=198
# @@protoc_insertion_point(module_scope)
